/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../synthesizer/synthesizer.module';
import * as import2 from '@angular/http/src/http_module';
import * as import3 from '@angular/http/src/backends/browser_xhr';
import * as import4 from '@angular/http/src/base_response_options';
import * as import5 from '@angular/http/src/backends/xhr_backend';
import * as import6 from '@angular/http/src/base_request_options';
import * as import7 from '../../synthesizer/services/pipeline/synthesis/midi-note.service';
import * as import8 from '../../synthesizer/services/pipeline/inputs/midi-input.service';
import * as import9 from '../../synthesizer/services/pipeline/inputs/drum-machine-input.service';
import * as import10 from '../../synthesizer/services/pipeline/inputs/note-input.service';
import * as import11 from '../../synthesizer/services/pipeline/synthesis/synthesis.service';
import * as import12 from '../../synthesizer/services/pipeline/outputs/audio-output.service';
import * as import13 from '../../synthesizer/services/pipeline/synthesis/drum-pcm-triggering.service';
import * as import14 from '../../synthesizer/services/pipeline/pipeline.service';
import * as import15 from '../../synthesizer/services/pipeline/processors/sequencer.service';
import * as import16 from '@angular/core/src/di/injector';
import * as import17 from '@angular/core/src/zone/ng_zone';
import * as import18 from '../../synthesizer/services/synth-stream-wrapper';
import * as import19 from '@angular/http/src/interfaces';
import * as import20 from '@angular/http/src/http';
class SynthesizerModuleInjector extends import0.NgModuleInjector<import1.SynthesizerModule> {
  _HttpModule_0:import2.HttpModule;
  _SynthesizerModule_1:import1.SynthesizerModule;
  __BrowserXhr_2:import3.BrowserXhr;
  __ResponseOptions_3:import4.BaseResponseOptions;
  __XSRFStrategy_4:any;
  __XHRBackend_5:import5.XHRBackend;
  __RequestOptions_6:import6.BaseRequestOptions;
  __Http_7:any;
  __MidiNoteService_8:import7.MidiNoteService;
  __MidiInputService_9:import8.MidiInputService;
  __DrumMachineInputService_10:import9.DrumMachineInputService;
  __NoteInputService_11:import10.NoteInputService;
  __SynthesisService_12:import11.SynthesisService;
  __AudioOutputService_13:import12.AudioOutputService;
  __DrumPCMTriggeringService_14:import13.DrumPCMTriggeringService;
  __PipelineService_15:import14.PipelineService;
  __SequencerService_16:import15.SequencerService;
  constructor(parent:import16.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _BrowserXhr_2():import3.BrowserXhr {
    if ((this.__BrowserXhr_2 == null)) { (this.__BrowserXhr_2 = new import3.BrowserXhr()); }
    return this.__BrowserXhr_2;
  }
  get _ResponseOptions_3():import4.BaseResponseOptions {
    if ((this.__ResponseOptions_3 == null)) { (this.__ResponseOptions_3 = new import4.BaseResponseOptions()); }
    return this.__ResponseOptions_3;
  }
  get _XSRFStrategy_4():any {
    if ((this.__XSRFStrategy_4 == null)) { (this.__XSRFStrategy_4 = import2._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_4;
  }
  get _XHRBackend_5():import5.XHRBackend {
    if ((this.__XHRBackend_5 == null)) { (this.__XHRBackend_5 = new import5.XHRBackend(this._BrowserXhr_2,this._ResponseOptions_3,this._XSRFStrategy_4)); }
    return this.__XHRBackend_5;
  }
  get _RequestOptions_6():import6.BaseRequestOptions {
    if ((this.__RequestOptions_6 == null)) { (this.__RequestOptions_6 = new import6.BaseRequestOptions()); }
    return this.__RequestOptions_6;
  }
  get _Http_7():any {
    if ((this.__Http_7 == null)) { (this.__Http_7 = import2.httpFactory(this._XHRBackend_5,this._RequestOptions_6)); }
    return this.__Http_7;
  }
  get _MidiNoteService_8():import7.MidiNoteService {
    if ((this.__MidiNoteService_8 == null)) { (this.__MidiNoteService_8 = new import7.MidiNoteService()); }
    return this.__MidiNoteService_8;
  }
  get _MidiInputService_9():import8.MidiInputService {
    if ((this.__MidiInputService_9 == null)) { (this.__MidiInputService_9 = new import8.MidiInputService(this.parent.get(import17.NgZone),this._Http_7)); }
    return this.__MidiInputService_9;
  }
  get _DrumMachineInputService_10():import9.DrumMachineInputService {
    if ((this.__DrumMachineInputService_10 == null)) { (this.__DrumMachineInputService_10 = new import9.DrumMachineInputService()); }
    return this.__DrumMachineInputService_10;
  }
  get _NoteInputService_11():import10.NoteInputService {
    if ((this.__NoteInputService_11 == null)) { (this.__NoteInputService_11 = new import10.NoteInputService()); }
    return this.__NoteInputService_11;
  }
  get _SynthesisService_12():import11.SynthesisService {
    if ((this.__SynthesisService_12 == null)) { (this.__SynthesisService_12 = new import11.SynthesisService(this._MidiNoteService_8)); }
    return this.__SynthesisService_12;
  }
  get _AudioOutputService_13():import12.AudioOutputService {
    if ((this.__AudioOutputService_13 == null)) { (this.__AudioOutputService_13 = new import12.AudioOutputService()); }
    return this.__AudioOutputService_13;
  }
  get _DrumPCMTriggeringService_14():import13.DrumPCMTriggeringService {
    if ((this.__DrumPCMTriggeringService_14 == null)) { (this.__DrumPCMTriggeringService_14 = new import13.DrumPCMTriggeringService(this._Http_7)); }
    return this.__DrumPCMTriggeringService_14;
  }
  get _PipelineService_15():import14.PipelineService {
    if ((this.__PipelineService_15 == null)) { (this.__PipelineService_15 = new import14.PipelineService(this._MidiNoteService_8,this._MidiInputService_9,this._DrumMachineInputService_10,this._NoteInputService_11,this._SynthesisService_12,this._AudioOutputService_13,this._DrumPCMTriggeringService_14)); }
    return this.__PipelineService_15;
  }
  get _SequencerService_16():import15.SequencerService {
    if ((this.__SequencerService_16 == null)) { (this.__SequencerService_16 = new import15.SequencerService(this.parent.get(import18.SynthStreamWrapper),this._PipelineService_15)); }
    return this.__SequencerService_16;
  }
  createInternal():import1.SynthesizerModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._SynthesizerModule_1 = new import1.SynthesizerModule();
    return this._SynthesizerModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import1.SynthesizerModule)) { return this._SynthesizerModule_1; }
    if ((token === import3.BrowserXhr)) { return this._BrowserXhr_2; }
    if ((token === import4.ResponseOptions)) { return this._ResponseOptions_3; }
    if ((token === import19.XSRFStrategy)) { return this._XSRFStrategy_4; }
    if ((token === import5.XHRBackend)) { return this._XHRBackend_5; }
    if ((token === import6.RequestOptions)) { return this._RequestOptions_6; }
    if ((token === import20.Http)) { return this._Http_7; }
    if ((token === import7.MidiNoteService)) { return this._MidiNoteService_8; }
    if ((token === import8.MidiInputService)) { return this._MidiInputService_9; }
    if ((token === import9.DrumMachineInputService)) { return this._DrumMachineInputService_10; }
    if ((token === import10.NoteInputService)) { return this._NoteInputService_11; }
    if ((token === import11.SynthesisService)) { return this._SynthesisService_12; }
    if ((token === import12.AudioOutputService)) { return this._AudioOutputService_13; }
    if ((token === import13.DrumPCMTriggeringService)) { return this._DrumPCMTriggeringService_14; }
    if ((token === import14.PipelineService)) { return this._PipelineService_15; }
    if ((token === import15.SequencerService)) { return this._SequencerService_16; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SynthesizerModuleNgFactory:import0.NgModuleFactory<import1.SynthesizerModule> = new import0.NgModuleFactory(SynthesizerModuleInjector,import1.SynthesizerModule);