/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../synthesizer/synthesizer.module';
import * as import2 from '@angular/http';
import * as import3 from '../../synthesizer/services/pipeline/synthesis/midi-note.service';
import * as import4 from '../../synthesizer/services/pipeline/inputs/midi-input.service';
import * as import5 from '../../synthesizer/services/pipeline/inputs/drum-machine-input.service';
import * as import6 from '../../synthesizer/services/pipeline/inputs/note-input.service';
import * as import7 from '../../synthesizer/services/pipeline/outputs/audio-output.service';
import * as import8 from '../../synthesizer/services/pipeline/synthesis/drum-pcm-triggering.service';
import * as import9 from '../../synthesizer/services/pipeline/pipeline.service';
import * as import10 from '../../synthesizer/services/pipeline/processors/sequencer.service';
import * as import11 from '../../synthesizer/services/synth-stream-wrapper';
class SynthesizerModuleInjector extends import0.ɵNgModuleInjector<import1.SynthesizerModule> {
  _HttpModule_0:import2.HttpModule;
  _SynthesizerModule_1:import1.SynthesizerModule;
  __BrowserXhr_2:import2.BrowserXhr;
  __ResponseOptions_3:import2.BaseResponseOptions;
  __XSRFStrategy_4:any;
  __XHRBackend_5:import2.XHRBackend;
  __RequestOptions_6:import2.BaseRequestOptions;
  __Http_7:any;
  __MidiNoteService_8:import3.MidiNoteService;
  __MidiInputService_9:import4.MidiInputService;
  __DrumMachineInputService_10:import5.DrumMachineInputService;
  __NoteInputService_11:import6.NoteInputService;
  __AudioOutputService_12:import7.AudioOutputService;
  __DrumPCMTriggeringService_13:import8.DrumPCMTriggeringService;
  __PipelineService_14:import9.PipelineService;
  __SequencerService_15:import10.SequencerService;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _BrowserXhr_2():import2.BrowserXhr {
    if ((this.__BrowserXhr_2 == null)) { (this.__BrowserXhr_2 = new import2.BrowserXhr()); }
    return this.__BrowserXhr_2;
  }
  get _ResponseOptions_3():import2.BaseResponseOptions {
    if ((this.__ResponseOptions_3 == null)) { (this.__ResponseOptions_3 = new import2.BaseResponseOptions()); }
    return this.__ResponseOptions_3;
  }
  get _XSRFStrategy_4():any {
    if ((this.__XSRFStrategy_4 == null)) { (this.__XSRFStrategy_4 = import2.ɵb()); }
    return this.__XSRFStrategy_4;
  }
  get _XHRBackend_5():import2.XHRBackend {
    if ((this.__XHRBackend_5 == null)) { (this.__XHRBackend_5 = new import2.XHRBackend(this._BrowserXhr_2,this._ResponseOptions_3,this._XSRFStrategy_4)); }
    return this.__XHRBackend_5;
  }
  get _RequestOptions_6():import2.BaseRequestOptions {
    if ((this.__RequestOptions_6 == null)) { (this.__RequestOptions_6 = new import2.BaseRequestOptions()); }
    return this.__RequestOptions_6;
  }
  get _Http_7():any {
    if ((this.__Http_7 == null)) { (this.__Http_7 = import2.ɵc(this._XHRBackend_5,this._RequestOptions_6)); }
    return this.__Http_7;
  }
  get _MidiNoteService_8():import3.MidiNoteService {
    if ((this.__MidiNoteService_8 == null)) { (this.__MidiNoteService_8 = new import3.MidiNoteService()); }
    return this.__MidiNoteService_8;
  }
  get _MidiInputService_9():import4.MidiInputService {
    if ((this.__MidiInputService_9 == null)) { (this.__MidiInputService_9 = new import4.MidiInputService(this.parent.get(import0.NgZone),this._Http_7)); }
    return this.__MidiInputService_9;
  }
  get _DrumMachineInputService_10():import5.DrumMachineInputService {
    if ((this.__DrumMachineInputService_10 == null)) { (this.__DrumMachineInputService_10 = new import5.DrumMachineInputService()); }
    return this.__DrumMachineInputService_10;
  }
  get _NoteInputService_11():import6.NoteInputService {
    if ((this.__NoteInputService_11 == null)) { (this.__NoteInputService_11 = new import6.NoteInputService()); }
    return this.__NoteInputService_11;
  }
  get _AudioOutputService_12():import7.AudioOutputService {
    if ((this.__AudioOutputService_12 == null)) { (this.__AudioOutputService_12 = new import7.AudioOutputService()); }
    return this.__AudioOutputService_12;
  }
  get _DrumPCMTriggeringService_13():import8.DrumPCMTriggeringService {
    if ((this.__DrumPCMTriggeringService_13 == null)) { (this.__DrumPCMTriggeringService_13 = new import8.DrumPCMTriggeringService(this._Http_7)); }
    return this.__DrumPCMTriggeringService_13;
  }
  get _PipelineService_14():import9.PipelineService {
    if ((this.__PipelineService_14 == null)) { (this.__PipelineService_14 = new import9.PipelineService(this._MidiNoteService_8,this._MidiInputService_9,this._DrumMachineInputService_10,this._NoteInputService_11,this._AudioOutputService_12,this._DrumPCMTriggeringService_13)); }
    return this.__PipelineService_14;
  }
  get _SequencerService_15():import10.SequencerService {
    if ((this.__SequencerService_15 == null)) { (this.__SequencerService_15 = new import10.SequencerService(this.parent.get(import11.SynthStreamWrapper),this._PipelineService_14)); }
    return this.__SequencerService_15;
  }
  createInternal():import1.SynthesizerModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._SynthesizerModule_1 = new import1.SynthesizerModule();
    return this._SynthesizerModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import1.SynthesizerModule)) { return this._SynthesizerModule_1; }
    if ((token === import2.BrowserXhr)) { return this._BrowserXhr_2; }
    if ((token === import2.ResponseOptions)) { return this._ResponseOptions_3; }
    if ((token === import2.XSRFStrategy)) { return this._XSRFStrategy_4; }
    if ((token === import2.XHRBackend)) { return this._XHRBackend_5; }
    if ((token === import2.RequestOptions)) { return this._RequestOptions_6; }
    if ((token === import2.Http)) { return this._Http_7; }
    if ((token === import3.MidiNoteService)) { return this._MidiNoteService_8; }
    if ((token === import4.MidiInputService)) { return this._MidiInputService_9; }
    if ((token === import5.DrumMachineInputService)) { return this._DrumMachineInputService_10; }
    if ((token === import6.NoteInputService)) { return this._NoteInputService_11; }
    if ((token === import7.AudioOutputService)) { return this._AudioOutputService_12; }
    if ((token === import8.DrumPCMTriggeringService)) { return this._DrumPCMTriggeringService_13; }
    if ((token === import9.PipelineService)) { return this._PipelineService_14; }
    if ((token === import10.SequencerService)) { return this._SequencerService_15; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SynthesizerModuleNgFactory:import0.NgModuleFactory<import1.SynthesizerModule> = new import0.NgModuleFactory<any>(SynthesizerModuleInjector,import1.SynthesizerModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2tyaW1wbGUvUHJvamVjdHMva2VuLXJpbXBsZS1vcGVuLXNvdXJjZS9uZy13ZWJhdWRpby1zeW50aGVzaXplci9zcmMvc3ludGhlc2l6ZXIvc3ludGhlc2l6ZXIubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2tyaW1wbGUvUHJvamVjdHMva2VuLXJpbXBsZS1vcGVuLXNvdXJjZS9uZy13ZWJhdWRpby1zeW50aGVzaXplci9zcmMvc3ludGhlc2l6ZXIvc3ludGhlc2l6ZXIubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
